[package]
name = "helius"
version = "0.2.1"
edition = "2021"
description = "An asynchronous Helius Rust SDK for building the future of Solana"
keywords = ["helius", "solana", "asynchronous-sdk", "das", "cryptocurrency"]
repository = "https://github.com/helius-labs/helius-rust-sdk"
docs = "https://docs.rs/helius/latest/helius/"
license = "MIT"
authors = ["0xIchigo <0xIchigo@protonmail.com>"]
readme = "README.md"
homepage = "https://www.helius.dev/"

[dependencies]
base64 = "0.22.1"
bincode = "1.3.3"
chrono = { version = "0.4.11", features = ["serde"] }
futures = "0.3.30"
futures-util = "0.3.30"
phf = { version = "0.11.2", features = ["macros"] }
rand = "0.8.5"
reqwest = { version = "0.12.3", features = ["json"] }
semver = "1.0.23"
serde = "1.0.198"
serde-enum-str = "0.4.0"
serde_json = "1.0.116"
solana-account-decoder = "1.18.12"
solana-client = "1.18.12"
solana-program = "1.18.12"
solana-rpc-client-api = "1.18.12"
solana-sdk = "1.18.11"
solana-transaction-status = "1.18.12"
thiserror = "1.0.58"
tokio = { version = "1.37.0", features = ["macros", "rt-multi-thread", "net"] }
tokio-stream = "0.1.15"
tokio-tungstenite = { version = "0.21.0", features = ["native-tls", "handshake"] }
url = "2.5.0"

[patch.crates-io]
solana-account-decoder = { git = "https://github.com/shamb0/solana.git", branch = "fix-issue-919-get-transaction", package = "solana-account-decoder" }
solana-client = { git = "https://github.com/shamb0/solana.git", branch = "fix-issue-919-get-transaction", package = "solana-client" }
solana-program = { git = "https://github.com/shamb0/solana.git", branch = "fix-issue-919-get-transaction", package = "solana-program" }
solana-rpc-client-api = { git = "https://github.com/shamb0/solana.git", branch = "fix-issue-919-get-transaction", package = "solana-rpc-client-api" }
solana-sdk = { git = "https://github.com/shamb0/solana.git", branch = "fix-issue-919-get-transaction", package = "solana-sdk" }
solana-transaction-status = { git = "https://github.com/shamb0/solana.git", branch = "fix-issue-919-get-transaction", package = "solana-transaction-status" }

[dev-dependencies]
mockito = "1.4.0"
